import React, { useState } from "react"
import "./Main.scss"

import Button from "../Button/Button"

const Main = () => {
  const [result, setResult] = useState("")
  const [operator, setOperator] = useState("")
  const [currentValue, setCurrentValue] = useState(0)
  return (
    <div className="main">
      <div className="main-result">
        <div className="main-result-info">{currentValue}</div>
      </div>
      <Button
        buttonClassName="main-button-grey"
        currentValue={currentValue}
        operator={operator}
        setOperator={setOperator}
        result={result}
        setResult={setResult}
        setCurrentValue={setCurrentValue}
      >
        AC
      </Button>
      <Button
        buttonClassName="main-button-grey"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
      >
        +/-
      </Button>
      <Button
        buttonClassName="main-button-grey"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
      >
        %
      </Button>
      <Button
        buttonClassName="main-button-orange"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
      >
        /
      </Button>
      <Button
        buttonClassName="main-button"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
      >
        7
      </Button>
      <Button
        buttonClassName="main-button"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
      >
        8
      </Button>
      <Button
        buttonClassName="main-button"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
      >
        9
      </Button>
      <Button
        buttonClassName="main-button-orange"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
      >
        x
      </Button>
      <Button
        buttonClassName="main-button"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
      >
        4
      </Button>
      <Button
        buttonClassName="main-button"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
      >
        5
      </Button>
      <Button
        buttonClassName="main-button"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
      >
        6
      </Button>
      <Button
        buttonClassName="main-button-orange"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
      >
        -
      </Button>
      <Button
        buttonClassName="main-button"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
      >
        1
      </Button>
      <Button
        buttonClassName="main-button"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
      >
        2
      </Button>
      <Button
        buttonClassName="main-button"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
      >
        3
      </Button>
      <Button
        buttonClassName="main-button-orange"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
      >
        +
      </Button>
      <Button
        buttonClassName="main-button-zero"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
      >
        0
      </Button>
      <Button
        buttonClassName="main-button"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
      >
        .
      </Button>
      <Button
        buttonClassName="main-button-orange"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
      >
        =
      </Button>
    </div>
  )
}

export default Main
