import React, { useState } from "react"
import "./Main.scss"

import Button from "../Button/Button"

const Main = () => {
  const [result, setResult] = useState("")
  const [operator, setOperator] = useState("")
  const [currentValue, setCurrentValue] = useState("")
  const [resetEqual, setResetEqual] = useState(false)
  return (
    <div className="main">
      <div className="main-result">
    <div className="main-result-info">{result} {operator} {currentValue}</div>
      </div>
      <Button
        buttonClassName="main-button-grey"
        currentValue={currentValue}
        operator={operator}
        setOperator={setOperator}
        result={result}
        setResult={setResult}
        setCurrentValue={setCurrentValue}
        setResetEqual={setResetEqual}
        resetEqual={resetEqual}
      >
        AC
      </Button>
      <Button
        buttonClassName="main-button-grey"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
        setResetEqual={setResetEqual}
        resetEqual={resetEqual}
      >
        C
      </Button>
      <Button
        buttonClassName="main-button-grey"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
        setResetEqual={setResetEqual}
        resetEqual={resetEqual}
      >
        %
      </Button>
      <Button
        buttonClassName="main-button-orange"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
        setResetEqual={setResetEqual}
        resetEqual={resetEqual}
      >
        /
      </Button>
      <Button
        buttonClassName="main-button"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
        setResetEqual={setResetEqual}
        resetEqual={resetEqual}
      >
        7
      </Button>
      <Button
        buttonClassName="main-button"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
        setResetEqual={setResetEqual}
        resetEqual={resetEqual}
      >
        8
      </Button>
      <Button
        buttonClassName="main-button"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
        setResetEqual={setResetEqual}
        resetEqual={resetEqual}
      >
        9
      </Button>
      <Button
        buttonClassName="main-button-orange"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
        setResetEqual={setResetEqual}
        resetEqual={resetEqual}
      >
        x
      </Button>
      <Button
        buttonClassName="main-button"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        setResetEqual={setResetEqual}
        resetEqual={resetEqual}
      >
        4
      </Button>
      <Button
        buttonClassName="main-button"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
        setResetEqual={setResetEqual}
        resetEqual={resetEqual}
      >
        5
      </Button>
      <Button
        buttonClassName="main-button"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
        setResetEqual={setResetEqual}
        resetEqual={resetEqual}
      >
        6
      </Button>
      <Button
        buttonClassName="main-button-orange"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
        setResetEqual={setResetEqual}
        resetEqual={resetEqual}
      >
        -
      </Button>
      <Button
        buttonClassName="main-button"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
        setResetEqual={setResetEqual}
        resetEqual={resetEqual}
      >
        1
      </Button>
      <Button
        buttonClassName="main-button"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
        setResetEqual={setResetEqual}
        resetEqual={resetEqual}
      >
        2
      </Button>
      <Button
        buttonClassName="main-button"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
        setResetEqual={setResetEqual}
        resetEqual={resetEqual}
      >
        3
      </Button>
      <Button
        buttonClassName="main-button-orange"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
        setResetEqual={setResetEqual}
        resetEqual={resetEqual}
      >
        +
      </Button>
      <Button
        buttonClassName="main-button-zero"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
        setResetEqual={setResetEqual}
        resetEqual={resetEqual}
      >
        0
      </Button>
      <Button
        buttonClassName="main-button"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
        setResetEqual={setResetEqual}
        resetEqual={resetEqual}
      >
        .
      </Button>
      <Button
        buttonClassName="main-button-orange"
        setCurrentValue={setCurrentValue}
        operator={operator}
        setOperator={setOperator}
        currentValue={currentValue}
        result={result}
        setResult={setResult}
        setResetEqual={setResetEqual}
        resetEqual={resetEqual}
      >
        =
      </Button>
    </div>
  )
}

export default Main
